### ISSUE TITLE
Add support for IDA 7.x

### ISSUE THREAD

**Issue by BullyWiiPlaza** [avast-tl/retdec-idaplugin#2]
Can you please implement support for IDA 7.x? The readme states that it's not supported, yet. Here is the porting guide you may want to follow: https://www.hex-rays.com/products/ida/7.0/docs/api70_porting_guide.shtml

Thank you.

**Comment by PeterMatula** [comment]
We will get to it sooner or later, but not right away.

If anyone is willing to give it a shot, go for it. It is free for all, until I assign this ticket to myself.

**Comment by messi89** [comment]
Hi guys 

is there any update to support IDA 7.x ?

**Comment by kirschju** [comment]
Hi all,

I've invested some hours to port the plugin to the new IDA API. The code compiles when including IDA SDK 7.0, but I am unable to link the resulting objects, because I'm lacking the 64-bit version of the [support package](https://github.com/avast-tl/retdec-idaplugin/releases/download/v0.4/retdec-idaplugin-v0.4-win.zip). I can compile the 64 bit versions of some of the libraries contained in the support package, however it is unclear to me how I would end up with a 64 bit version of `retdec.lib` to link against. It doesn't seem to be part of what is produced when compiling retdec from the main repo. Any pointers (or, even better, a 64 bit version of the support package) would be greatly appreciated.

**Comment by PeterMatula** [comment]
@kirschju The library naming in this case is not the best. `retdec.lib` is not from the main RetDec repository, but it is this: https://github.com/s3rvac/retdec-cpp. You can try it with it, maybe you will succeed. I will try to implement `retdec-idaplugin`'s CMake build system in a way that would get and build all the support libraries automatically. Pre-built support package would therefore not be needed, and your job would be much easier. However, I'm not able to tell how hard it will be (how long it will take), since I suspect it might be tricky.

**Comment by Zibri** [comment]
please support ida 7.0 !

**Comment by 0xBEEEF** [comment]
It would be especially cool if the plugin would run with the IDA 7.0 freeware! Then you would have the perfect combination.

**Comment by PeterMatula** [comment]
@0xBEEEF I think there is no reason why a 7.0 plugin (once we have it) would not run in freeware IDA. So yes, when we rewrite it from SDK 6.6 to 7.x, it should work.

**Comment by PeterMatula** [comment]
Fixed.

The current implementation is only a rewrite to IDA 7.0 SDK. No improvements. We dropped remote decompilation through API. There are several new tickets with improvements and bugs.

The new version does not work in freeware IDA 7.0 (see #22).
