### ISSUE TITLE
Windows install fails

### ISSUE THREAD

**Issue by BigJim** [avast-tl/retdec-idaplugin#25]
Despite following the Windows install instructions to the letter in the users guide, the plugin will not install properly apparently. Installed Python 3.6 followed by pip3 install of Pygments.
When invoked it asks for a non-existent ".sh" file (which obviously wouldn't run on Windows anyhow). Added Python 3.6 path to my PATH variable (making it the one and only default Python binary) and that didn't change anything.

**Comment by PeterMatula** [comment]
Thanks for this issue. Our documentation was not clear about this. At the moment, you also need to install standalone RetDec in order to use RetDec IDA plugin. I updated both the user guide and v0.5 release. The instructions should be a bit more clear now.

In future, we would like to get rid of bash scripts, use purely Python, and distribute RetDec itself together with RetDec IDA plugin.
