### ISSUE TITLE
Can help compile a mac version, A Mac IDA7.0  is here

### ISSUE THREAD

**Issue by chago** [avast-tl/retdec-idaplugin#57]
https://pan.baidu.com/s/1z_qPUuPWJqVkrEwtYhSKPA Extraction: ugd4

**Comment by PeterMatula** [comment]
1. That link is not working for me - I don't see anything useful.
2. I don't think I will be much help, I don't have IDA for macOS.

**Comment by chago** [comment]
OK

**Comment by PeterMatula** [comment]
Well, if you paste here error log, or describe your problem in more detail, I can try to help. But right now you provided no useful info.

**Comment by PeterMatula** [comment]
Oh, now I get it. I need to put that `ugd4` code to the prompt to see the content. I thought the link is not working.

However, I was expecting a failed compilation log or something, not a macOS version of IDA. I cannot use that to build macOS version of this plugin because it is against IDA license. You will have to try yourself.
