### ISSUE TITLE
IDA7.7 v1.0 release does not work

### ISSUE THREAD

**Issue by mahmoudimus** [avast-tl/retdec-idaplugin#73]
On startup, I see this error:

```
LoadLibrary(C:\Users\MalwareBytesInc\AppData\Roaming\Hex-Rays\IDA Pro\plugins\retdec64.dll) error: The specified module could not be found.
C:\Users\MalwareBytesInc\AppData\Roaming\Hex-Rays\IDA Pro\plugins\retdec64.dll: can't load file
```

Any idea how to debug?

**Comment by s0l3nya** [comment]
Having the same issue with 8.2; don't suppose @mahmoudimus found a workaround?

Tried the latest release and building from scratch with cmake & visual studio and also added to the plugins config. 

Output in IDA is:
LoadLibrary(C:\Program Files\IDA Pro 8.2\plugins\retdec64.dll) error: Module not found.
C:\Program Files\IDA Pro 8.2\plugins\retdec64.dll: can't load file

**Comment by BingoHeelah** [comment]
It appears to have to do with libcrypto. Loading the plugin itself into ida yields a handful of imports for that library.

**Comment by s0l3nya** [comment]
I fixed this by installing the full version of win openssl; I previously had the light version which wouldn't work even if you manually set the PATH.

Plugin still doesn't work though; now getting the 'Unable to parse decompilation output: The document is empty' error.

This was on IDA 8.2, with a freshly compiled plugin off the 82SDK.

**Comment by 77920** [comment]
> I fixed this by installing the full version of win openssl; I previously had the light version which wouldn't work even if you manually set the PATH.
> 
> Plugin still doesn't work though; now getting the 'Unable to parse decompilation output: The document is empty' error.
> 
> This was on IDA 8.2, with a freshly compiled plugin off the 82SDK.

This is correct installing openSSL full version corrects it. However when hitting ctrl + D it wants a binary file when trying to decompile pesudo code. Anyone know why this is? version 1.0 never wanted you to select a .EXE file.

**Comment by mahmoudimus** [comment]
Indeed, OpenSSL full installation does resolve this issue but I get the same error that @s0l3nya is experiencing: "Unable to parse decompilation output: The document is empty"

**Comment by PeterMatula** [comment]
Looks like several problems are mentioned here:
* RetDec plugin not loaded - due to a missing OpenSSL installation. Install full OpenSSL as RetDec uses some of its functions. I believe this is mentioned somewhere in the PDF that comes with the release.
* `Unable to parse decompilation output: The document is empty` error - as also reported in #70, which I closed with [this](https://github.com/avast/retdec-idaplugin/issues/70#issuecomment-1539809393). Unfortunately RetDec has problems with processing some files, especially if they are big. However nothing can be done with this easily. RetDec itlsef would have to be majorly optimized. I would like to track only IDA plugin related issues in this project, and have all the other issues in [RetDec issues](https://github.com/avast/retdec/issues).
* `However when hitting ctrl + D it wants a binary file when trying to decompile pesudo code` - as mentioned somewhere else, the plugin needs the original binary file. It does not extract the bytes to work with from IDA. This might be the reason for this problem. If the binary file was present, and the problem still persist please open a specific issue for it and try to describe it in detail so that it is possible to reproduce it.
